/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as ProfessorIndexRouteImport } from './routes/professor.index'
import { Route as ProfessorTurmaIdRouteImport } from './routes/Professor.turma.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/aluno/',
  path: '/aluno/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorIndexRoute = ProfessorIndexRouteImport.update({
  id: '/professor/',
  path: '/professor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorTurmaIdRoute = ProfessorTurmaIdRouteImport.update({
  id: '/Professor/turma/$id',
  path: '/Professor/turma/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aluno/': typeof AlunoIndexRoute
  '/professor/': typeof ProfessorIndexRoute
  '/Professor/turma/$id': typeof ProfessorTurmaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aluno': typeof AlunoIndexRoute
  '/professor': typeof ProfessorIndexRoute
  '/Professor/turma/$id': typeof ProfessorTurmaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aluno/': typeof AlunoIndexRoute
  '/professor/': typeof ProfessorIndexRoute
  '/Professor/turma/$id': typeof ProfessorTurmaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/aluno/' | '/professor/' | '/Professor/turma/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/aluno' | '/professor' | '/Professor/turma/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/aluno/'
    | '/professor/'
    | '/Professor/turma/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
  ProfessorIndexRoute: typeof ProfessorIndexRoute
  ProfessorTurmaIdRoute: typeof ProfessorTurmaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/aluno'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/': {
      id: '/professor/'
      path: '/professor'
      fullPath: '/professor/'
      preLoaderRoute: typeof ProfessorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Professor/turma/$id': {
      id: '/Professor/turma/$id'
      path: '/Professor/turma/$id'
      fullPath: '/Professor/turma/$id'
      preLoaderRoute: typeof ProfessorTurmaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AlunoIndexRoute: AlunoIndexRoute,
  ProfessorIndexRoute: ProfessorIndexRoute,
  ProfessorTurmaIdRoute: ProfessorTurmaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
